---
- name: Cleanup
  shell:  |
    systemctl stop prometheus
    userdel prometheus
    groupdel prometheus
    rm -rf /etc/prometheus
    rm -rf /var/lib/prometheus
    rm -r prometheus-2.43.0.linux-amd64.tar.gz
    rm -rf prometheus-2.43.0.linux-amd64
    rm -r /etc/systemd/system/prometheus.service

  ignore_errors: True

- name: Updating System Packages for Ubuntu
  shell:  |
    apt update
    groupadd --system prometheus
    useradd -s /sbin/nologin --system -g prometheus prometheus
  when: ansible_distribution=="Ubuntu"

- name: Updating System Packages for CentOS
  shell:  |
    yum update
    groupadd --system prometheus
    useradd -s /sbin/nologin --system -g prometheus prometheus
  when: ansible_distribution=="CentOS"

- name: Creating a System User for Prometheus
  shell:  |
    mkdir /etc/prometheus
    mkdir /var/lib/prometheus

- name: Creating Directories for Prometheus
  shell:  |
    wget https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz

- name: Downloading Prometheus and Extracting Files
  shell:  |
    tar vxf prometheus*.tar.gz

- name: Navigating to the Prometheus Directory
  shell:  |
    cd ~
    cd /home/crstnrfee/prometheus-2.43.0.linux-amd64

- name: Moving the Binary Files & Set Owner
  shell:  |
    cd ~
    cd /home/crstnrfee/prometheus-2.43.0.linux-amd64
    mv prometheus /usr/local/bin
    mv promtool /usr/local/bin
    chown prometheus:prometheus /usr/local/bin/prometheus
    chown prometheus:prometheus /usr/local/bin/promtool

- name: Moving the Configuration Files & Set Owner
  shell:  |
    cd /home/crstnrfee/prometheus-2.43.0.linux-amd64
    mv consoles /etc/prometheus
    mv console_libraries /etc/prometheus
    mv prometheus.yml /etc/prometheus
    chown prometheus:prometheus /etc/prometheus
    chown -R prometheus:prometheus /etc/prometheus/consoles
    chown -R prometheus:prometheus /etc/prometheus/console_libraries
    chown -R prometheus:prometheus /var/lib/prometheus

- name: Creating Prometheus Systemd Service
  copy:
    src: prometheus.service
    dest: "/etc/systemd/system"

- name: Reloading Systemd
  shell:  |
    systemctl daemon-reload

- name: Starting Prometheus Service
  shell:  |
    systemctl enable prometheus
    systemctl start prometheus

- name: Accessing Prometheus Web Interface for Ubuntu
  shell:  |
    ufw allow 9090/tcp
  when: ansible_distribution=="Ubuntu"

- name: Accessing Prometheus Web Interface for CentOS
  shell:  |
    firewall-cmd --zone=public --add-port=9090/tcp --permanent
  when: ansible_distribution=="CentOS"





